version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum install -y httpd
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: no